name: Register-Tenant-Workflow

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every minute
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  register-tenant-job:
    runs-on: ubuntu-latest
    environment: sandbox


    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
        pip install python-dotenv
        pip install certifi
        pip install dataclasses  
        pip install pydantic   

    - name: Fetch PENDING check point 
      id: fetch_check_point
      run: python getCheckPoint.py PENDING tenant     
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
    
    - name: Calculate cluxter index
      id: calculate_cluster_index
      run: echo "cluster_index=001" >> "$GITHUB_OUTPUT"
    
    - name: Print GITHUB_OUTPUT path
      run: |
        echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
        cat "$GITHUB_OUTPUT"
        
    - name: Print output variable
      run: |
        echo "cluster_index: ${{ steps.calculate_cluster_index.outputs.cluster_index }}"
        echo "execution_id: ${{ steps.fetch_check_point.outputs.execution_id }}"
        echo "tenant: ${{ steps.fetch_check_point.outputs.tenant_id }}"
    
    - name: Update check point to REGISTERED  
      run: python updateCheckPoint.py "REGISTERED" "tenant" ${{ steps.fetch_check_point.outputs.execution_id }} ${{ steps.calculate_cluster_index.outputs.cluster_index }}
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}
