name: Register-Tenant-Workflow

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
  workflow_dispatch:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  register-tenant-job:
    runs-on: ubuntu-latest
    environment: sandbox


    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
        pip install python-dotenv

    - name: Run query script
      run: python getCheckPoint.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_COLLECTION: ${{ secrets.MONGO_COLLECTION }}